version: 1.0
app:
  # Set the build version ID to deploy for the "Build, deploy, and run" 
  # scenario. If the value is set to an empty string ("") the application
  # is not deployed.
  version: "bc4f73c7-c41d-4ea1-b786-51986cf1836d"

  endpoints: public
  

  
